### ISSUE TITLE
Lag After A hit

### ISSUE THREAD

**Issue by Drqp** [SiroQ/PvPParticles#5]
After using the mod for the first time i had noticed that when you had hit an entity it would lag me 60 frames lower. This entity was even a zombie. i have tried using different verions of forge and optifine and even no optifine but it still lags pls help

**Comment by koeigiantic** [comment]
The same thing happens to me either. Sometimes it happens and sometimes it doesn't

**Comment by Drqp** [comment]
ik and i rly want to use the mod as there are too many hackers in ranked skywars

**Comment by SiroQ** [comment]
Can you send me video?

**Comment by Drqp** [comment]
uploading to youtube will link it

**Comment by Drqp** [comment]
2nd Linl:https://youtu.be/DntShCKViOI

**Comment by SiroQ** [comment]
Fixed
